"""Make NUM_AI and NUM_ATA primary keys

Revision ID: 32d9c709a2a4
Revises: b60ec7cdbc9c
Create Date: 2026-08-30 21:26:19.977552

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32d9c709a2a4"
down_revision: Union[str, Sequence[str], None] = "b60ec7cdbc9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recurso_primeira_instancia",
        "NUM_AI",
        existing_type=mysql.VARCHAR(length=15),
        nullable=False,
    )
    op.alter_column(
        "recurso_primeira_instancia",
        "NUM_ATA",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
    )
    op.drop_index(op.f("NUM_AI"), table_name="recurso_primeira_instancia")
    op.drop_column("recurso_primeira_instancia", "ID")
    op.create_primary_key(
        "pk_recurso_primeira_instancia",
        "recurso_primeira_instancia",
        ["NUM_AI", "NUM_ATA"],
    )

    op.alter_column(
        "recurso_segunda_instancia",
        "NUM_AI",
        existing_type=mysql.VARCHAR(length=15),
        nullable=False,
    )
    op.drop_index(op.f("NUM_AI"), table_name="recurso_segunda_instancia")
    op.drop_column("recurso_segunda_instancia", "ID")
    op.create_primary_key(
        "pk_recurso_segunda_instancia", "recurso_segunda_instancia", ["NUM_AI"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "pk_recurso_segunda_instancia", "recurso_segunda_instancia", type_="primary"
    )
    op.add_column(
        "recurso_segunda_instancia",
        sa.Column(
            "ID", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
    )
    op.create_primary_key(
        "pk_recurso_segunda_instancia_old", "recurso_segunda_instancia", ["ID"]
    )
    op.create_index(
        op.f("NUM_AI"), "recurso_segunda_instancia", ["NUM_AI"], unique=True
    )
    op.alter_column(
        "recurso_segunda_instancia",
        "NUM_AI",
        existing_type=mysql.VARCHAR(length=15),
        nullable=True,
    )

    op.drop_constraint(
        "pk_recurso_primeira_instancia", "recurso_primeira_instancia", type_="primary"
    )
    op.add_column(
        "recurso_primeira_instancia",
        sa.Column(
            "ID", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
    )
    op.create_primary_key(
        "pk_recurso_primeira_instancia_old", "recurso_primeira_instancia", ["ID"]
    )
    op.create_index(
        op.f("NUM_AI"), "recurso_primeira_instancia", ["NUM_AI"], unique=True
    )
    op.alter_column(
        "recurso_primeira_instancia",
        "NUM_ATA",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
    )
    op.alter_column(
        "recurso_primeira_instancia",
        "NUM_AI",
        existing_type=mysql.VARCHAR(length=15),
        nullable=True,
    )
    # ### end Alembic commands ###
