"""production-state

Revision ID: 833cf2a5b507
Revises: 46226f422f07
Create Date: 2026-08-28 09:18:55.881232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '833cf2a5b507'
down_revision: Union[str, Sequence[str], None] = '46226f422f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linha', 'COMPARTILHADA',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('linha', 'LINH_ATIV_EMPR',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_constraint(op.f('CONSTRAINT_1'), 'linha', type_='check')
    op.alter_column('recurso_primeira_instancia', 'RESULTADO',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('recurso_segunda_instancia', 'RESULTADO',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('veiculos', 'VEIC_ATIV_EMPR',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('veiculos', 'VEIC_ATIV_EMPR',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('recurso_segunda_instancia', 'RESULTADO',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('recurso_primeira_instancia', 'RESULTADO',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_check_constraint(op.f('CONSTRAINT_1'), 'linha', '`COMPARTILHADA` in (0,1)')
    op.alter_column('linha', 'LINH_ATIV_EMPR',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('linha', 'COMPARTILHADA',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    # ### end Alembic commands ###
