"""add_data_baixa

Revision ID: ffc8c99c6b0e
Revises: 833cf2a5b507
Create Date: 2026-08-28 09:45:17.116601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc8c99c6b0e'
down_revision: Union[str, Sequence[str], None] = '833cf2a5b507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linha', sa.Column('DAT_BAIX', sa.DateTime(), nullable=True))
    op.add_column('veiculos', sa.Column('DAT_BAIX', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veiculos', 'DAT_BAIX')
    op.drop_column('linha', 'DAT_BAIX')
    # ### end Alembic commands ###
